version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: mock_ekyc
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

  minio:
    hostname: minio
    image: quay.io/minio/minio
    command: minio server /data/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - minio_data:/data/

volumes:
  pg_data:
  minio_data: